[[setup]]
== Setup

So, you get a brand new Ontrack instance. You can login with the default `admin` / `admin` user and the home page appears desperately empty.

We'll start to feed Ontrack later on, but first, we need to secure and configure the instance.

[[security]]
=== Security

[[security-admin-password]]
==== Changing the admin password

Log as `admin` (using the `admin` password), and go to the _user menu_ on the top right corner, and select _User profile_.

In the _Change password_ section, enter `admin` as the old password and setup a new and strong password for the `admin` user.

[CAUTION]
====
Take care to store this new password in a safe place (like a password manager) since, as of now, this password cannot be recovered without the help of the Ontrack support.
====

[[security-methods]]
==== A better security

Now that the super `admin` user is secured, you may start thinking about the way you will allow other users to authenticate into your Ontrack instance.

Out-of-the-box, Ontrack allows several authentication methods:

* https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#authentication-built-in[_Built-in authentication_]: you manually define groups & users in Ontrack itself. Users can then connect and change their password. While being very simple to start with, this does not really scale and does not integrate with any other authentication method you may have in your organization.

* https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#authentication-ldap[_LDAP authentication_]: Ontrack can use an external LDAP for authentication and group management.

* https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#authentication-openid[_Open ID Connect authentication_]: Ontrack can use an Open ID Connect compatible identify provider, like https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#authentication-okta[Okta] or https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#authentication-keycloak[Keycloak]

[[application-properties]]
=== Application properties

On request, and if the package you've bought allows it, you can ask for additional https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#configuration-properties[application properties] to be set for your instance.

Create an `application.yaml` file based on the https://static.nemerosa.net/ontrack/release/latest/docs/doc/index.html#configuration-properties[available configuration properties] and provide it to the <<support,support>>. When these application properties have been put in place, your instance will be restarted automatically in the hour with the new parameters.
